#### 目录介绍
- 01.未捕获的异常
- 02.链式异常




### 好消息
- 博客笔记大汇总【16年3月到至今】，包括Java基础及深入知识点，Android技术博客，Python学习笔记等等，还包括平时开发中遇到的bug汇总，当然也在工作之余收集了大量的面试题，长期更新维护并且修正，持续完善……开源的文件是markdown格式的！同时也开源了生活博客，从12年起，积累共计N篇[近100万字，陆续搬到网上]，转载请注明出处，谢谢！
- **链接地址：https://github.com/yangchong211/YCBlogs**
- 如果觉得好，可以star一下，谢谢！当然也欢迎提出建议，万事起于忽微，量变引起质变！



### 01.未捕获的异常
- 没有被程序捕获的所有异常，最终都会交由Java运行时系统提供的默认处理程序捕获。默认处理程序会显示一个描述异常的字符串，输出异常发生的堆栈踪迹并终止程序。
- 例如，运行如下代码：
    ```
    public class Demo {
    	public static void main(String[] args) {
    		int a=520/0;
    	}
    }
    ```
- 生成的异常信息：
    ```
    Exception in thread "main" java.lang.ArithmeticException: / by zero
    	at Demo.main(Demo.java:5)
    ```
- 抛出的异常的类型是Exception的子类ArithmeticException，即算术异常，更具体地描述了发生的错误类型。Java提供了一些能与可能产生的各种运行时错误相匹配的内置异常类型。[博客](https://github.com/yangchong211/YCBlogs)




### 02.链式异常
- 链式异常用于为异常关联另一个异常，第二个异常用于描述当前异常产生的原因。
    - 例如，某个方法从文件读取数值来作为除法运算的除数，由于发生了I/O错误导致获取到的数值是0，从而导致了ArithmeticException异常。
    - 如果想要让代码调用者知道背后的原因是I/O错误，使用链式异常就可以来处理这种情况以及其他存在多层异常的情况。
- 为了使用链式异常，Throwable有两个构造函数和两个方法用于处理这种情况。
    - 两个构造函数：
    ```
    Throwable(Throwable cause)
    Throwable(String message, Throwable cause)
    ```
    - cause即是用于指定引发当前异常的背后原因，message则可以用于同时指定异常描述。
    - 两个方法：
    ```
    Throwable getCause()
    Throwable initCause(Throwable cause)
    ```
        - getCause() 方法用来返回引发当前异常的异常，如果不存在背后异常则返回null。
        initCause(Throwable cause)方法将cause和明面上的异常关联到一起，并返回对异常的引用。因此可以在创建异常之后将异常和背后异常关联到一起。但是，背后异常只能设置一次，即initCause(Throwablecause)方法只能调用一次。此外，如果通过构造函数设置了背后异常，也不能再使用该方法来设置背后异常了。
- 案例展示
    - 例如，参照如下代码：
    ```
    public class Demo {
    	
    	public static void demo(){
    		NullPointerException nullPointerException=new NullPointerException("nullPointer");
    		nullPointerException.initCause(new ArithmeticException("Arithmetic"));
    		throw nullPointerException;
    	}
    
    	public static void main(String[] args) {
    		try {
    			demo();
    		} catch (Exception e) {
    			System.out.println(e.getMessage());
    			System.out.println(e.getCause().getMessage());
    		}
    	}
    }
    ```
    - 运行结果是：[博客](https://github.com/yangchong211/YCBlogs)
    ```
    nullPointer
    Arithmetic
    ```
    - 链式异常可以包含所需要的任意深度，但是，过长的异常链可能是一种不良的设计。







### 其他介绍
#### 01.关于博客汇总链接
- 1.[技术博客汇总](https://www.jianshu.com/p/614cb839182c)
- 2.[开源项目汇总](https://blog.csdn.net/m0_37700275/article/details/80863574)
- 3.[生活博客汇总](https://blog.csdn.net/m0_37700275/article/details/79832978)
- 4.[喜马拉雅音频汇总](https://www.jianshu.com/p/f665de16d1eb)
- 5.[其他汇总](https://www.jianshu.com/p/53017c3fc75d)



#### 02.关于我的博客
- 我的个人站点：www.yczbj.org，www.ycbjie.cn
- github：https://github.com/yangchong211
- 知乎：https://www.zhihu.com/people/yczbj/activities
- 简书：http://www.jianshu.com/u/b7b2c6ed9284
- csdn：http://my.csdn.net/m0_37700275
- 喜马拉雅听书：http://www.ximalaya.com/zhubo/71989305/
- 开源中国：https://my.oschina.net/zbj1618/blog
- 泡在网上的日子：http://www.jcodecraeer.com/member/content_list.php?channelid=1
- 邮箱：yangchong211@163.com
- 阿里云博客：https://yq.aliyun.com/users/article?spm=5176.100- 239.headeruserinfo.3.dT4bcV
- segmentfault头条：https://segmentfault.com/u/xiangjianyu/articles
- 掘金：https://juejin.im/user/5939433efe88c2006afa0c6e





